name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - 'env.yml'
jobs:
  setup-deployment-env:
    name: Setup Deployment Environment
    runs-on: ubuntu-latest
    outputs:
      deployment-environments: ${{ steps.get-deployment-environment.outputs.deployment-environments }}
    steps:
      - name: Checkout config
        uses: actions/checkout@v4

      - name: Get environments
        id: get-deployment-environment
        run: echo "deployment-environments=$(jq --compact-output '.environments' ./config/deployment-environment.json)" >> $GITHUB_OUTPUT

  pack:
    name: Pack Payu
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.payu.outputs.name }}
      version: ${{ steps.payu.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Payu Version
        id: payu
        run: |
          VERSION=$(yq eval '.dependencies[] | select(contains("accessnri::payu")) | split("==") | .[1]' env.yml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "name=payu-$VERSION" >> $GITHUB_OUTPUT

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1.7.0
        with:
          micromamba-version: '1.5.3-0'
          environment-file: env.yml
          environment-name: ${{ steps.payu.outputs.name }}
          generate-run-shell: true

      - name: Create Pack and Lockfile
        shell: micromamba-shell {0}
        run: |
          conda pack
          conda-lock lock --file env.yml --platform linux-64 --micromamba --lockfile ${{ steps.payu.outputs.name }}.conda-lock.yml

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.payu.outputs.name }}
          if-no-files-found: error
          path: |
            ${{ steps.payu.outputs.name }}.tar.gz
            ${{ steps.payu.outputs.name }}.conda-lock.yml

  deploy:
    runs-on: ubuntu-latest
    needs:
      - pack
      - setup-deployment-env
    strategy:
      fail-fast: false
      matrix:
        deployment-environment: ${{ fromJson(needs.setup-deployment-env.outputs.deployment-environments) }}
    environment: ${{ matrix.deployment-environment }}
    env:
      NAME: ${{ needs.pack.outputs.name }}
      VERSION: ${{ needs.pack.outputs.version }}
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.NAME }}

      - uses: access-nri/actions/.github/actions/setup-ssh@main
        id: ssh
        with:
          hosts: |
            ${{ secrets.HOST_DATA }}
            ${{ secrets.HOST }}
          private-key: ${{ secrets.SSH_KEY }}

      - name: Copy to ${{ matrix.deployment-environment }}
        run: |
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            ${{ env.NAME }}.tar.gz \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ vars.PACK_LOCATION }}

      - name: Deploy to ${{ matrix.deployment-environment }}
        env:
          PAYU_ENVIRONMENT_LOCATION: ${{ vars.DEPLOYMENT_LOCATION }}/${{ env.VERSION }}
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          mkdir ${{ env.PAYU_ENVIRONMENT_LOCATION }}
          if [ $? -ne 0 ]; then
            # Replace pre-existing environment
            echo "::warning::Removing pre-existing environment at: ${{ env.PAYU_ENVIRONMENT_LOCATION }}"
            rm -rf "${{ env.PAYU_ENVIRONMENT_LOCATION }}"
            mkdir ${{ env.PAYU_ENVIRONMENT_LOCATION }}
          fi
          tar -xzf ${{ vars.PACK_LOCATION }}/${{ env.NAME }}.tar.gz -C ${{ env.PAYU_ENVIRONMENT_LOCATION }}
          source ${{ env.PAYU_ENVIRONMENT_LOCATION }}/bin/activate
          conda-unpack
          payu --version
          source ${{ env.PAYU_ENVIRONMENT_LOCATION }}/bin/deactivate
          ln -sf ${{ vars.MODULE_LOCATION }}/.common ${{ vars.MODULE_LOCATION }}/${{ env.VERSION }}
          EOT

      # Release
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ env.VERSION }}
          name: Payu ${{ env.VERSION }}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./${{ env.NAME }}.tar.gz
            ./${{ env.NAME }}.conda-lock.yml
