name: Update common modulefiles on Gadi
on:
  push:
    branches:
      - main
    paths:
      - 'modules/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Gadi
    steps:
      - uses: actions/checkout@v4

      - uses: access-nri/actions/.github/actions/setup-ssh@main
        id: ssh
        with:
          hosts: |
            ${{ secrets.HOST_DATA }}
          private-key: ${{ secrets.SSH_KEY }}

      - name: Copy modulefiles to Gadi
        run: |
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \ 
            modules/  \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ vars.MODULE_LOCATION }}
