name: Update common modulefiles on Gadi
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'modules/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Gadi
    steps:
      - uses: actions/checkout@v4

      - uses: access-nri/actions/.github/actions/setup-ssh@main
        id: ssh
        with:
          hosts: |
            ${{ secrets.HOST_DATA }}
          private-key: ${{ secrets.SSH_KEY }}

      - name: Generate release modulesfiles
        run: |
          mkdir -p release/modules
          sed 's|{{MODULE_LOCATION}}|'"${{ vars.MODULE_LOCATION }}"'|g' modules/.common > release/modules/.common
          sed 's|{{APPS_LOCATION}}|'"${{ vars.APPS_LOCATION }}"'|g' modules/env.sh > release/modules/env.sh
          chmod +x release/modules/env.sh

      - name: Generate pre-release modulesfiles
        run: |
          mkdir -p prerelease/modules
          sed 's|{{MODULE_LOCATION}}|'"${{ vars.PRERELEASE_MODULE_LOCATION }}"'|g' modules/.common > prerelease/modules/.common
          sed 's|{{APPS_LOCATION}}|'"${{ vars.PRERELEASE_APPS_LOCATION }}"'|g' modules/env.sh > prerelease/modules/env.sh
          chmod +x prerelease/modules/env.sh

      - name: Copy modulefiles to Gadi
        run: |
          # Rsync release modulefiles
          rsync -rvp -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            release/modules/ \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ vars.MODULE_LOCATION }}

          # Rsync development modulefiles
          rsync -rvp -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            prerelease/modules/ \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ vars.PRERELEASE_MODULE_LOCATION }}
